[package]
name = "whale"
version = "0.1.0"
edition = "2021"
keywords = ["reactive", "incremental", "dependency-tracking"]
description = "A lock-free, dependency-tracking primitive for incremental computation."
categories = ["data-structures"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/ryo33/whale"
repository = "https://github.com/ryo33/whale"
readme = "README.md"

[features]
default = ["serde"]
serde = ["dep:serde", "papaya/serde", "ahash/serde"]

[dependencies]
ahash = "0.8"
papaya = { version = "0.2" }
serde = { version = "1", features = ["derive", "rc"], optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
